# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "benepay-development"
  config.vm.box_download_insecure = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
	vb.name = "benepay_dev"
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
	  vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  # Create a private network, which allows host-only access to the machine using a specific IP.
  config.vm.network "private_network", ip: "192.168.30.205"

  # Share an additional folder to the guest VM. The first argument is the path on the host to the actual folder.
  # The second argument is the path on the guest to mount the folder.
  config.vm.synced_folder("../projects", "/var/www/html", :mount_options => ["dmode=777", "fmode=777"])
  config.vm.synced_folder("./", "/vagrant", :mount_options => ["dmode=777", "fmode=777"])

  # Define the bootstrap file: A (shell) script that runs after first setup of your box (= provisioning)
  config.vm.provision :shell, path: "bootstrap.sh", run: "once"

end
